<a href="https://colab.research.google.com/github/Viniciusvto/Aula-1---Analise-de-Dados-com-Pandas/blob/main/aula_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aula 1** - Análise de Dados com Pandas:

Ensinar a carregar arquivos CSV no Google Colab, realizar leitura e visualização inicial de dados com Pandas. O aluno começará a manipular bases reais de dados com comandos simples de análise.

In [78]:
import pandas as pd

In [79]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv") #peguei meus dados

In [80]:
df.head(10) # estou lendo as 10 primeiras linhas

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [81]:
df.info()# tipos de dados, titulos das colunas se estão preenchidos ou não

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [82]:
df.describe() #é uma função que me da dados númericos min, max, total e etc

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [83]:
df.shape # um atributo que me da a dimensão dos arquivos. linhas, colunas.

(133349, 11)

In [84]:
linhas,  colunas = df.shape [0], df.shape [1] # estou relacionando linhas com a posição 0 e colunas com a posição 1 e transferindo os dados para esses valores
print ("linhas:", linhas) # estou printando os valores de linhas
print ("colunas:", colunas) # Estou printando os valores de colunas

linhas: 133349
colunas: 11

In [85]:
df.columns #listar o nome das colunas

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [86]:
# Dicionário de mapeamento para traduzir os nomes das colunas
traducao_colunas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

# Renomear as colunas do DataFrame
df.rename(columns=traducao_colunas, inplace=True)

# Exibir os nomes das colunas traduzidas
print(df.columns)

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [87]:
df["senioridade"].value_counts() #analise de colunas (nivel_experiencia)
#Senior
#Pleno
#Junior
#executivo

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [88]:
df["contrato"].value_counts() #Analisando a coluna (tipo_emprego)
#Full-Time
#CT - Contrato Temporario
#PT - Meio Período
#Freela

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [89]:
df["remoto"].value_counts()
# 0 trabalhos que são presenciais
# 100 remotos
# 50 hibridas

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [90]:
df["tamanho_empresa"].value_counts()
#medium
#large
#small

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [91]:
# Mapeamento das categorias de senioridade para português
traducao_senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

# Substituir os valores na coluna 'senioridade'
df['senioridade'] = df['senioridade'].replace(traducao_senioridade)

# Exibir a contagem dos valores traduzidos
print(df['senioridade'].value_counts())

senioridade
Senior       77241
Pleno        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

In [92]:
# Mapeamento das categorias de contrato para português
traducao_contrato = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato Temporário',
    'PT': 'Meio Período',
    'FL': 'Freelancer'
}

# Substituir os valores na coluna 'contrato'
df['contrato'] = df['contrato'].replace(traducao_contrato)

# Exibir a contagem dos valores traduzidos
print(df['contrato'].value_counts())

contrato
Tempo Integral         132563
Contrato Temporário       394
Meio Período              376
Freelancer                 16
Name: count, dtype: int64

In [93]:
# Mapeamento das categorias de tamanho_empresa para português
traducao_tamanho_empresa = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}

# Substituir os valores na coluna 'tamanho_empresa'
df['tamanho_empresa'] = df['tamanho_empresa'].replace(traducao_tamanho_empresa)

# Exibir a contagem dos valores traduzidos
print(df['tamanho_empresa'].value_counts())

tamanho_empresa
Médio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [94]:
# Mapeamento das categorias de remoto para português
traducao_remoto = {
    0: 'Presencial',
    100: 'Remoto',
    50: 'Híbrido'
}

# Substituir os valores na coluna 'remoto'
df['remoto'] = df['remoto'].replace(traducao_remoto)

# Exibir a contagem dos valores traduzidos
print(df['remoto'].value_counts())

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [95]:
df.head(10)

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio
5,2025.0,Junior,Tempo Integral,Data Engineer,80000,USD,80000,US,Presencial,US,Médio
6,2025.0,Senior,Tempo Integral,Data Scientist,185000,USD,185000,US,Presencial,US,Médio
7,2025.0,Senior,Tempo Integral,Data Scientist,148000,USD,148000,US,Presencial,US,Médio
8,2025.0,Pleno,Tempo Integral,Data Scientist,135000,USD,135000,CA,Presencial,CA,Médio
9,2025.0,Pleno,Tempo Integral,Data Scientist,108000,USD,108000,CA,Presencial,CA,Médio

In [96]:
# Exibir a contagem dos valores na coluna 'residencia'
print(df['residencia'].value_counts().head(10)) # Mostrando os 10 valores mais frequentes

residencia
US    119579
CA      5238
GB      3711
AU       517
NL       404
DE       385
FR       369
LT       338
AT       297
ES       265
Name: count, dtype: int64

In [97]:
df.head(10)

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio
5,2025.0,Junior,Tempo Integral,Data Engineer,80000,USD,80000,US,Presencial,US,Médio
6,2025.0,Senior,Tempo Integral,Data Scientist,185000,USD,185000,US,Presencial,US,Médio
7,2025.0,Senior,Tempo Integral,Data Scientist,148000,USD,148000,US,Presencial,US,Médio
8,2025.0,Pleno,Tempo Integral,Data Scientist,135000,USD,135000,CA,Presencial,CA,Médio
9,2025.0,Pleno,Tempo Integral,Data Scientist,108000,USD,108000,CA,Presencial,CA,Médio

In [98]:
df.describe(include= "object")
# count= quantos valores temos para a coluna
# unique= tipos unicos temos 4 tipos de contratos(tempo integral, contrato temporario, meio periodo e frella )
# residencia 102 paises
# top = qual informação é mais frequente
# freq = é o calculo da frequencia por exemplo o senior apareceu 77241 vezes

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,Médio
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [99]:
df.describe()

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

Aula 02

In [100]:
df.isnull() #aqui ele mostra os dados faltantes como True caso haja algum

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [101]:
df.isnull().sum() # ele somou tudo que era nulo e encontrou 10 campos nulos no valor ano

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [102]:
df['ano'].unique() # aqui eu vejos os valores unicos dentro da coluna ano (nan é um valor nulo no python)

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [103]:
df[df.isnull().any(axis=1)] # aqui eu exibo as linhas que estão com o valor nulo na coluna (ano)

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,Médio
59692,NaN,Pleno,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Médio
59710,NaN,Junior,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Médio
59759,NaN,Senior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Médio
59789,NaN,Senior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,Médio
131000,NaN,Senior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Médio
131006,NaN,Senior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Médio
133054,NaN,Junior,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Pleno,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Pleno,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,Grande

In [111]:
df_limpo = df.dropna()  #criei outro dataframe para limpar os dados faltantes da coluna ano

In [114]:
df_limpo.isnull().sum() # fiz a somatoria novamente para ver se os valores nulos ainda estão aparentes

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [115]:
df_limpo.head() #outro ponto é a coluna ano que está com um ponto após o quarto digito

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [116]:
df_limpo.info() # o tipo dessa variavel ano é float64

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  float64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

In [125]:
#converter o tipo de uma variavel (ano=float64) para (ano=int)

df_limpo = df_limpo.assign (ano = df_limpo['ano'].astype('int64'))
# o meu df_limpo vai receber df limpo reconfigurando(assing) toda a coluna ano anterior mas com o novo tipo de int

df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

Criar um dataframe do zero para exercitar criar uma média de valores faltantes de uma tabela.

In [104]:

import numpy as np # importo a biblioteca numpy para manipualar valores

df_salarios = pd.DataFrame({
    'nome':['Ana','Bruno','Carlos','Daniele','Fulano',], # crio a coluna nome
    'salario':[4000,np.nan,5000,np.nan,100000]}) #Crio a coluna salario e deixo alguns valores nulos


df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
# logica da media acima: df_salario é a nossa base e salario_media é a nosso nova coluna
#então = dataframe_salarios = coluna salario(filtra valores nulus) e cria uma média dentro do df_salarios coluna salario com duas casas decimais de arredondamento



df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())


df_salarios# acresentei um salario de 100000 para entender como a mediana suavisa melhor em relação a média que pode não representar a realidade

      nome   salario  salario_media  salario_mediana
0      Ana    4000.0        4000.00           4000.0
1    Bruno       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3  Daniele       NaN       36333.33           5000.0
4   Fulano  100000.0      100000.00         100000.0

In [105]:
df_temperatura = pd.DataFrame({
    'dia':['Segunda','Terca','Quarta','Quinta','Sexta'],
    'temp':[30,np.nan,np.nan,28,27]
})

df_temperatura['preenchido_ffill'] = df_temperatura ['temp'].ffill()
'''o ffill completa com o valor anterior, no caso terça e quarta estavam nulos então
foi feito o complemento com o valor anterior
'''
df_temperatura

       dia  temp  preenchido_ffill
0  Segunda  30.0              30.0
1    Terca   NaN              30.0
2   Quarta   NaN              30.0
3   Quinta  28.0              28.0
4    Sexta  27.0              27.0

In [110]:
'''criando um novo dataframe chamado df_cidades e criando duas colunas(nome e cidade)
 e criando uma coluna chamada cidade_corrigida '''

df_cidades =  pd.DataFrame({
    'nome': ['Ana','Bruno','Carlos','Daniele','Fulano'],
    'cidade': ['São Paulo',np.nan,'Curitiba',np.nan,'Belém']
    })

df_cidades['cidade_corrigida'] = df_cidades['cidade'].fillna('Não informado')

df_cidades

      nome     cidade cidade_corrigida
0      Ana  São Paulo        São Paulo
1    Bruno        NaN    Não informado
2   Carlos   Curitiba         Curitiba
3  Daniele        NaN    Não informado
4   Fulano      Belém            Belém